<?php

namespace ContainerYKxvHWe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HpPZV0EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HpPZV0E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matiereRepository' => ['privates', 'App\\Repository\\MatiereRepository', 'getMatiereRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'matiereRepository' => 'App\\Repository\\MatiereRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.HpPZV0E'])) {
            return $container->privates['.service_locator.HpPZV0E'];
        }

        return $container->privates['.service_locator.HpPZV0E'] = $instance;
    }
}
