<?php

namespace ContainerYKxvHWe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WtrA_M3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wtrA.M3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'matiere' => ['privates', '.errored..service_locator.wtrA.M3.App\\Entity\\Matiere', NULL, 'Cannot autowire service ".service_locator.wtrA.M3": it needs an instance of "App\\Entity\\Matiere" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'matiere' => 'App\\Entity\\Matiere',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.wtrA.M3'])) {
            return $container->privates['.service_locator.wtrA.M3'];
        }

        return $container->privates['.service_locator.wtrA.M3'] = $instance;
    }
}
