<?php

namespace ContainerYKxvHWe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Iop9ZwdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Iop9Zwd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailService' => ['privates', 'App\\Service\\EmailNotificationService', 'getEmailNotificationServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'matiere' => ['privates', '.errored..service_locator.Iop9Zwd.App\\Entity\\Matiere', NULL, 'Cannot autowire service ".service_locator.Iop9Zwd": it needs an instance of "App\\Entity\\Matiere" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'emailService' => 'App\\Service\\EmailNotificationService',
            'entityManager' => '?',
            'matiere' => 'App\\Entity\\Matiere',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.Iop9Zwd'])) {
            return $container->privates['.service_locator.Iop9Zwd'];
        }

        return $container->privates['.service_locator.Iop9Zwd'] = $instance;
    }
}
