<?php

namespace ContainerYKxvHWe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EF9xMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e_f_9xM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cours' => ['privates', '.errored..service_locator.e_f_9xM.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.e_f_9xM": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'cours' => 'App\\Entity\\Cours',
            'entityManager' => '?',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.e_f_9xM'])) {
            return $container->privates['.service_locator.e_f_9xM'];
        }

        return $container->privates['.service_locator.e_f_9xM'] = $instance;
    }
}
