<?php

namespace ContainerYKxvHWe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nk5ftDGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nk5ftDG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'matiere' => ['privates', '.errored..service_locator.nk5ftDG.App\\Entity\\Matiere', NULL, 'Cannot autowire service ".service_locator.nk5ftDG": it needs an instance of "App\\Entity\\Matiere" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'matiere' => 'App\\Entity\\Matiere',
        ]);

        if (isset($container->privates['.service_locator.nk5ftDG'])) {
            return $container->privates['.service_locator.nk5ftDG'];
        }

        return $container->privates['.service_locator.nk5ftDG'] = $instance;
    }
}
