<?php

namespace ContainerYKxvHWe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ENnjP3gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eNnjP3g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eNnjP3g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cours' => ['privates', '.errored..service_locator.eNnjP3g.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.eNnjP3g": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'stripeService' => ['privates', 'App\\Service\\StripeService', 'getStripeServiceService', true],
        ], [
            'cours' => 'App\\Entity\\Cours',
            'stripeService' => 'App\\Service\\StripeService',
        ]);
    }
}
