<?php

namespace ContainerYKxvHWe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailNotificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailNotificationService' shared autowired service.
     *
     * @return \App\Service\EmailNotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmailNotificationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Service\\EmailNotificationService'])) {
            return $container->privates['App\\Service\\EmailNotificationService'];
        }
        $b = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\Service\\EmailNotificationService'])) {
            return $container->privates['App\\Service\\EmailNotificationService'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Service\\EmailNotificationService'])) {
            return $container->privates['App\\Service\\EmailNotificationService'];
        }
        $d = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\EmailNotificationService'])) {
            return $container->privates['App\\Service\\EmailNotificationService'];
        }

        $instance = new \App\Service\EmailNotificationService(new \Symfony\Component\Mailer\Mailer($a, $b, $c), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $d);

        if (isset($container->privates['App\\Service\\EmailNotificationService'])) {
            return $container->privates['App\\Service\\EmailNotificationService'];
        }

        return $container->privates['App\\Service\\EmailNotificationService'] = $instance;
    }
}
