<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matiere extends \App\Entity\Matiere implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'code_matiere' => [parent::class, 'code_matiere', null, 16],
        "\0".parent::class."\0".'cours' => [parent::class, 'cours', null, 16],
        "\0".parent::class."\0".'date_creation' => [parent::class, 'date_creation', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'niveau' => [parent::class, 'niveau', null, 16],
        "\0".parent::class."\0".'nom_matiere' => [parent::class, 'nom_matiere', null, 16],
        "\0".parent::class."\0".'section' => [parent::class, 'section', null, 16],
        'code_matiere' => [parent::class, 'code_matiere', null, 16],
        'cours' => [parent::class, 'cours', null, 16],
        'date_creation' => [parent::class, 'date_creation', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'niveau' => [parent::class, 'niveau', null, 16],
        'nom_matiere' => [parent::class, 'nom_matiere', null, 16],
        'section' => [parent::class, 'section', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
