<?php

namespace ContainerAVoht97;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6phKzWAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6phKzWA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6phKzWA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matiere' => ['privates', '.errored..service_locator.6phKzWA.App\\Entity\\Matiere', NULL, 'Cannot autowire service ".service_locator.6phKzWA": it needs an instance of "App\\Entity\\Matiere" but this type has been excluded in "config/services.yaml".'],
        ], [
            'matiere' => 'App\\Entity\\Matiere',
        ]);
    }
}
