<?php

namespace ContainerAVoht97;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GbcXfTAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GbcXfTA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.GbcXfTA'])) {
            return $container->privates['.service_locator.GbcXfTA'];
        }

        return $container->privates['.service_locator.GbcXfTA'] = $instance;
    }
}
