<?php

namespace ContainerAVoht97;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestDoctrineCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestDoctrineCommand' shared autowired service.
     *
     * @return \App\Command\TestDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'TestDoctrineCommand.php';

        $container->privates['App\\Command\\TestDoctrineCommand'] = $instance = new \App\Command\TestDoctrineCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:test-doctrine');
        $instance->setDescription('Test Doctrine connection and fetch all users');

        return $instance;
    }
}
