<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAVoht97\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAVoht97/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAVoht97.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAVoht97\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAVoht97\App_KernelDevDebugContainer([
    'container.build_hash' => 'AVoht97',
    'container.build_id' => '8c98d79d',
    'container.build_time' => 1771809957,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAVoht97');
